from .cutieCentral.llama import Llama
from .cutieCentral.donkey import Donkey
from .cutieCentral.goat import Goat
from .cutieCentral.cow import Cow
from .cutieCentral.pig import Pig
from .slitheringDen.snake import Snake
from .pondVillage.frog import Frog
from .pondVillage.fish import Fish
from .cutieCentral.hamster import Hamster
from .slitheringDen.lizard import Lizard
from .pondVillage.mallard import Mallard
from .pondVillage.goldfish import Goldfish
from .pondVillage.swan import Swan
from .slitheringDen.snail import Snail
from .animals import Animal
